import type { Metadata } from "next";
import Link from "next/link";
import { site } from "@/lib/site";

export const metadata: Metadata = { title: "Voorwaarden", description: "Praktische voorwaarden voor een verblijf in Ático Hilsol." };

export default function TermsPage() {
  return <main className="legal"><Link className="legal-back" href="/">Ático Hilsol</Link><article><p className="eyebrow">Voorwaarden</p><h1>Praktische verblijfsvoorwaarden</h1><p className="legal-lead">Een aanvraag via deze website is een vraag naar beschikbaarheid en vormt op zichzelf nog geen definitieve boeking.</p><h2>Bevestiging</h2><p>Een verblijf is pas definitief zodra de eigenaar de periode, prijs en praktische afspraken uitdrukkelijk heeft bevestigd. De website toont indicatieve seizoenstarieven en geen live beschikbaarheid.</p><h2>Prijs en betaling</h2><p>De definitieve prijs, betaalwijze en betaaltermijnen worden rechtstreeks met de verhuurder afgesproken. De website verwerkt geen betalingen. Een terugbetaalbare waarborg kan deel uitmaken van de bevestigde afspraak.</p><h2>Minimumverblijf</h2><p>De huidige richtlijn is een minimumverblijf van {site.minNights} nachten en maximaal {site.maxGuests} gasten, tenzij schriftelijk anders overeengekomen.</p><h2>Aankomst en vertrek</h2><p>De huidige richttijden zijn check-in vanaf 16:00 en check-out uiterlijk om 10:00. Afwijkingen zijn enkel geldig na persoonlijke bevestiging.</p><h2>Annulatie en huisregels</h2><p>De concrete annulatievoorwaarden, huisregels en eventuele bijkomende afspraken worden samen met de definitieve reserveringsbevestiging meegedeeld. Die bevestigde afspraken hebben voorrang op algemene informatie op deze website.</p><h2>Contact</h2><p>Vragen kunnen rechtstreeks naar <a href={`mailto:${site.email}`}>{site.email}</a>.</p><p className="legal-date">Versie: 21 augustus 2026</p></article></main>;
}
